services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    env_file:
      - ../../.env
    environment:
      - SERVER_PORT=2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
      - ./plugins:/opt/Lavalink/plugins
      - ./youtube-cookies.txt:/opt/Lavalink/youtube-cookies.txt:ro
    ports:
      - "2333:2333"
    restart: unless-stopped
